name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-verify-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.17'
        otp-version: '27'

    - name: Install dependencies
      run: mix deps.get

    - name: Build package
      run: mix package

    - name: Verify package
      run: mix test
